apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api
        image: <seu-usuario>/projeto-k8s-backend:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secret
---
apiVersion: v1
kind: Service
metadata:
  name: flask-api
  namespace: app
spec:
  selector:
    app: flask-api
  ports:
    - port: 80
      targetPort: 5000
  type: ClusterIP
